apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
      name: hello-world
    spec:
      containers:
        - name: $
          image: picoded/hello-world
          imagePullPolicy: Always
